language: rust
os:
  - linux
  - windows
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      export LIBCLANG_PATH="C:\\Program Files\\LLVM\\\\bin"
      export TARGET="x86_64-pc-windows-msvc"
    else
      export TARGET="x86_64-unknown-linux-gnu"
    fi
  - rustup target add "$TARGET"
  - cargo build --verbose --target "$TARGET" --all
  - cargo test --verbose --target "$TARGET" --all
  - cargo package --verbose --target "$TARGET"
deploy:
  skip_cleanup: true
  provider: cargo
  token:
    secure: IWHvXIwT+43rrfBBIds0QfSo0UxNK6rPN6APKiXI9e/KELTetPbfeBXztvu+8KjAyqdX8hXJDrvTSheBF/EA9oPTFQqS1mmFR/16AAYRAKUOkBgTKvFMtYQy+LdTQdllBJPi/sQxnFKeK0f4BevKgbv/kruOmnA2P4NG8EIoMkJCLTfv3HroNm8+aGznVIU/qqolmJDygcBdN/ksLLAHMcqDKKhF/66bs/B7yTyQAWnP+GmRWq0FRJKwR+LREEdV/fa/dP3ZuwSwlgFUfrPB3oEV+b9iiZEn4bMKOjGUyx9cKaN31XVcGCYygUqLaYtslQMvzd9iVvun4Jk8Aex7WFEF+oWg2o5aYSa9W8Hu63noiqyket7M3rn9xwdKDJGm7KDnocG41X4QotPebfHPF10pG7P2dAs+YnCx59MfdlH8Ya8jbQXKyOp2qo2b52R0+iyhqZ3Ukp/n4gHX9/uD+2SFWS8uPtvEXy+OGyx1KjsJxpQbSbQCjuLhqyTPMG76pgyy+BbsiEdeqViTor9jlrELuqXzGN+lToJV1Du9Z321ZGxP7Bgd2DsK/H135skblBTeOqBrE3zb58jwZaEA/HX+NbaSxjI/uM3d5rcdWfFmYYlKlWrzF7Hyyh93gqjWFyViE5coOK6APVn/wK1zrIhYxTUl8XFqLdleRWB1VdI=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_RUST_VERSION = stable && $TRAVIS_OS_NAME = linux
