[package]
name = "libftd2xx"
version = "0.1.0"
authors = ["Alex M. <7845120+newAM@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libftd2xx_ffi = { path = "../libftd2xx-ffi-rs/" }
libc = "0.2.71"
