[package]
name = "libftd2xx"
version = "0.1.0"
authors = ["Alex M. <alexmgit@protonmail.com>"]
edition = "2018"
description = "Rust safe wrapper around the libftd2xx-ffi crate."
keywords = ["ftdi", "usb"]
categories = ["api-bindings", "hardware-support"]
readme = "README.md"
repository = "https://github.com/newAM/libftd2xx-rs/"
documentation = "https://docs.rs/libftd2xx"
license = "MIT"

[dependencies]
libftd2xx-ffi = "0.1"
libc = "0.2.71"

[badges]
travis-ci = { repository = "newAM/libftd2xx-rs" }
maintenance = { status = "as-is" }
